server:
  session-timeout: 1800
  tomcat:
    max-threads: 1000
  port: 8083


  #配置web页面入口
magic-api:
  web: /magic/web # UI请求的界面以及UI服务地址
  auto-import-module: db,model,test



  http2:
    enabled: true
  undertow:
    io-threads: 16
    worker-threads: 800
    buffer-size: 1024
    direct-buffers: true



spring:
  jackson:
    date-format: 'yyyy-MM-dd HH:mm:ss'
    time-zone: GMT+8
      #serialization:
    #write-dates-as-timestamps: false
  profiles:
    active: dev
  application:
    name: util
  servlet:
  #multipart:
  #max-file-size: 30Mb
  #max-request-size: 30Mb
  main:
    allow-bean-definition-overriding: true
  devtools:
    restart:
      enabled: true
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml



redis:
  host: localhost
  port: 6379
  password:
  # 连接超时时间（毫秒）
  timeout: 10000
  jedis:
    pool:
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 10
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 100
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1

